; Auto-generated. Do not edit!


(cl:in-package steward-msg)


;//! \htmlinclude MotorsResult.msg.html

(cl:defclass <MotorsResult> (roslisp-msg-protocol:ros-message)
  ((final_velocity
    :reader final_velocity
    :initarg :final_velocity
    :type cl:fixnum
    :initform 0)
   (final_angle
    :reader final_angle
    :initarg :final_angle
    :type cl:float
    :initform 0.0)
   (final_Y
    :reader final_Y
    :initarg :final_Y
    :type cl:float
    :initform 0.0))
)

(cl:defclass MotorsResult (<MotorsResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MotorsResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MotorsResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name steward-msg:<MotorsResult> is deprecated: use steward-msg:MotorsResult instead.")))

(cl:ensure-generic-function 'final_velocity-val :lambda-list '(m))
(cl:defmethod final_velocity-val ((m <MotorsResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader steward-msg:final_velocity-val is deprecated.  Use steward-msg:final_velocity instead.")
  (final_velocity m))

(cl:ensure-generic-function 'final_angle-val :lambda-list '(m))
(cl:defmethod final_angle-val ((m <MotorsResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader steward-msg:final_angle-val is deprecated.  Use steward-msg:final_angle instead.")
  (final_angle m))

(cl:ensure-generic-function 'final_Y-val :lambda-list '(m))
(cl:defmethod final_Y-val ((m <MotorsResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader steward-msg:final_Y-val is deprecated.  Use steward-msg:final_Y instead.")
  (final_Y m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MotorsResult>) ostream)
  "Serializes a message object of type '<MotorsResult>"
  (cl:let* ((signed (cl:slot-value msg 'final_velocity)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 65536) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    )
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'final_angle))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'final_Y))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MotorsResult>) istream)
  "Deserializes a message object of type '<MotorsResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'final_velocity) (cl:if (cl:< unsigned 32768) unsigned (cl:- unsigned 65536))))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'final_angle) (roslisp-utils:decode-single-float-bits bits)))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'final_Y) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MotorsResult>)))
  "Returns string type for a message object of type '<MotorsResult>"
  "steward/MotorsResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MotorsResult)))
  "Returns string type for a message object of type 'MotorsResult"
  "steward/MotorsResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MotorsResult>)))
  "Returns md5sum for a message object of type '<MotorsResult>"
  "016f502c77a87052898c214a72532802")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MotorsResult)))
  "Returns md5sum for a message object of type 'MotorsResult"
  "016f502c77a87052898c214a72532802")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MotorsResult>)))
  "Returns full string definition for message of type '<MotorsResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int16 final_velocity~%float32 final_angle~%float32 final_Y~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MotorsResult)))
  "Returns full string definition for message of type 'MotorsResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int16 final_velocity~%float32 final_angle~%float32 final_Y~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MotorsResult>))
  (cl:+ 0
     2
     4
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MotorsResult>))
  "Converts a ROS message object to a list"
  (cl:list 'MotorsResult
    (cl:cons ':final_velocity (final_velocity msg))
    (cl:cons ':final_angle (final_angle msg))
    (cl:cons ':final_Y (final_Y msg))
))
