; Auto-generated. Do not edit!


(cl:in-package steward-msg)


;//! \htmlinclude MotorsGoal.msg.html

(cl:defclass <MotorsGoal> (roslisp-msg-protocol:ros-message)
  ((goal_velocity
    :reader goal_velocity
    :initarg :goal_velocity
    :type cl:fixnum
    :initform 0)
   (angle_limits
    :reader angle_limits
    :initarg :angle_limits
    :type cl:float
    :initform 0.0)
   (Y_limits
    :reader Y_limits
    :initarg :Y_limits
    :type cl:float
    :initform 0.0))
)

(cl:defclass MotorsGoal (<MotorsGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MotorsGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MotorsGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name steward-msg:<MotorsGoal> is deprecated: use steward-msg:MotorsGoal instead.")))

(cl:ensure-generic-function 'goal_velocity-val :lambda-list '(m))
(cl:defmethod goal_velocity-val ((m <MotorsGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader steward-msg:goal_velocity-val is deprecated.  Use steward-msg:goal_velocity instead.")
  (goal_velocity m))

(cl:ensure-generic-function 'angle_limits-val :lambda-list '(m))
(cl:defmethod angle_limits-val ((m <MotorsGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader steward-msg:angle_limits-val is deprecated.  Use steward-msg:angle_limits instead.")
  (angle_limits m))

(cl:ensure-generic-function 'Y_limits-val :lambda-list '(m))
(cl:defmethod Y_limits-val ((m <MotorsGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader steward-msg:Y_limits-val is deprecated.  Use steward-msg:Y_limits instead.")
  (Y_limits m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MotorsGoal>) ostream)
  "Serializes a message object of type '<MotorsGoal>"
  (cl:let* ((signed (cl:slot-value msg 'goal_velocity)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 65536) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    )
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'angle_limits))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'Y_limits))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MotorsGoal>) istream)
  "Deserializes a message object of type '<MotorsGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'goal_velocity) (cl:if (cl:< unsigned 32768) unsigned (cl:- unsigned 65536))))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'angle_limits) (roslisp-utils:decode-single-float-bits bits)))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'Y_limits) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MotorsGoal>)))
  "Returns string type for a message object of type '<MotorsGoal>"
  "steward/MotorsGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MotorsGoal)))
  "Returns string type for a message object of type 'MotorsGoal"
  "steward/MotorsGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MotorsGoal>)))
  "Returns md5sum for a message object of type '<MotorsGoal>"
  "d8d57bb6887a089db071ec31ad56c0e1")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MotorsGoal)))
  "Returns md5sum for a message object of type 'MotorsGoal"
  "d8d57bb6887a089db071ec31ad56c0e1")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MotorsGoal>)))
  "Returns full string definition for message of type '<MotorsGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int16 goal_velocity~%float32 angle_limits~%float32 Y_limits~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MotorsGoal)))
  "Returns full string definition for message of type 'MotorsGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int16 goal_velocity~%float32 angle_limits~%float32 Y_limits~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MotorsGoal>))
  (cl:+ 0
     2
     4
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MotorsGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'MotorsGoal
    (cl:cons ':goal_velocity (goal_velocity msg))
    (cl:cons ':angle_limits (angle_limits msg))
    (cl:cons ':Y_limits (Y_limits msg))
))
