// Auto-generated. Do not edit!

// (in-package steward.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class MotorsFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.actual_velocity = null;
      this.actual_angle = null;
      this.actual_Y = null;
    }
    else {
      if (initObj.hasOwnProperty('actual_velocity')) {
        this.actual_velocity = initObj.actual_velocity
      }
      else {
        this.actual_velocity = 0;
      }
      if (initObj.hasOwnProperty('actual_angle')) {
        this.actual_angle = initObj.actual_angle
      }
      else {
        this.actual_angle = 0.0;
      }
      if (initObj.hasOwnProperty('actual_Y')) {
        this.actual_Y = initObj.actual_Y
      }
      else {
        this.actual_Y = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type MotorsFeedback
    // Serialize message field [actual_velocity]
    bufferOffset = _serializer.int16(obj.actual_velocity, buffer, bufferOffset);
    // Serialize message field [actual_angle]
    bufferOffset = _serializer.float32(obj.actual_angle, buffer, bufferOffset);
    // Serialize message field [actual_Y]
    bufferOffset = _serializer.float32(obj.actual_Y, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type MotorsFeedback
    let len;
    let data = new MotorsFeedback(null);
    // Deserialize message field [actual_velocity]
    data.actual_velocity = _deserializer.int16(buffer, bufferOffset);
    // Deserialize message field [actual_angle]
    data.actual_angle = _deserializer.float32(buffer, bufferOffset);
    // Deserialize message field [actual_Y]
    data.actual_Y = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 10;
  }

  static datatype() {
    // Returns string type for a message object
    return 'steward/MotorsFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '3315109a593fd61ca499c8580578c0ca';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    int16 actual_velocity
    float32 actual_angle
    float32 actual_Y
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new MotorsFeedback(null);
    if (msg.actual_velocity !== undefined) {
      resolved.actual_velocity = msg.actual_velocity;
    }
    else {
      resolved.actual_velocity = 0
    }

    if (msg.actual_angle !== undefined) {
      resolved.actual_angle = msg.actual_angle;
    }
    else {
      resolved.actual_angle = 0.0
    }

    if (msg.actual_Y !== undefined) {
      resolved.actual_Y = msg.actual_Y;
    }
    else {
      resolved.actual_Y = 0.0
    }

    return resolved;
    }
};

module.exports = MotorsFeedback;
