// Generated by gencpp from file steward/MotorsResult.msg
// DO NOT EDIT!


#ifndef STEWARD_MESSAGE_MOTORSRESULT_H
#define STEWARD_MESSAGE_MOTORSRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace steward
{
template <class ContainerAllocator>
struct MotorsResult_
{
  typedef MotorsResult_<ContainerAllocator> Type;

  MotorsResult_()
    : final_velocity(0)
    , final_angle(0.0)
    , final_Y(0.0)  {
    }
  MotorsResult_(const ContainerAllocator& _alloc)
    : final_velocity(0)
    , final_angle(0.0)
    , final_Y(0.0)  {
  (void)_alloc;
    }



   typedef int16_t _final_velocity_type;
  _final_velocity_type final_velocity;

   typedef float _final_angle_type;
  _final_angle_type final_angle;

   typedef float _final_Y_type;
  _final_Y_type final_Y;




  typedef boost::shared_ptr< ::steward::MotorsResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::steward::MotorsResult_<ContainerAllocator> const> ConstPtr;

}; // struct MotorsResult_

typedef ::steward::MotorsResult_<std::allocator<void> > MotorsResult;

typedef boost::shared_ptr< ::steward::MotorsResult > MotorsResultPtr;
typedef boost::shared_ptr< ::steward::MotorsResult const> MotorsResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::steward::MotorsResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::steward::MotorsResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace steward

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'steward': ['/home/pawel/AGV/Pepperl/src/steward/msg', '/home/pawel/AGV/Pepperl/devel/share/steward/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::steward::MotorsResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::steward::MotorsResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::steward::MotorsResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::steward::MotorsResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::steward::MotorsResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::steward::MotorsResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::steward::MotorsResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "016f502c77a87052898c214a72532802";
  }

  static const char* value(const ::steward::MotorsResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x016f502c77a87052ULL;
  static const uint64_t static_value2 = 0x898c214a72532802ULL;
};

template<class ContainerAllocator>
struct DataType< ::steward::MotorsResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "steward/MotorsResult";
  }

  static const char* value(const ::steward::MotorsResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::steward::MotorsResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
int16 final_velocity\n\
float32 final_angle\n\
float32 final_Y\n\
";
  }

  static const char* value(const ::steward::MotorsResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::steward::MotorsResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.final_velocity);
      stream.next(m.final_angle);
      stream.next(m.final_Y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorsResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::steward::MotorsResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::steward::MotorsResult_<ContainerAllocator>& v)
  {
    s << indent << "final_velocity: ";
    Printer<int16_t>::stream(s, indent + "  ", v.final_velocity);
    s << indent << "final_angle: ";
    Printer<float>::stream(s, indent + "  ", v.final_angle);
    s << indent << "final_Y: ";
    Printer<float>::stream(s, indent + "  ", v.final_Y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STEWARD_MESSAGE_MOTORSRESULT_H
