// Generated by gencpp from file steward/Motors.msg
// DO NOT EDIT!


#ifndef STEWARD_MESSAGE_MOTORS_H
#define STEWARD_MESSAGE_MOTORS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace steward
{
template <class ContainerAllocator>
struct Motors_
{
  typedef Motors_<ContainerAllocator> Type;

  Motors_()
    : motor1_pwm(0)
    , motor2_pwm(0)  {
    }
  Motors_(const ContainerAllocator& _alloc)
    : motor1_pwm(0)
    , motor2_pwm(0)  {
  (void)_alloc;
    }



   typedef int16_t _motor1_pwm_type;
  _motor1_pwm_type motor1_pwm;

   typedef int16_t _motor2_pwm_type;
  _motor2_pwm_type motor2_pwm;




  typedef boost::shared_ptr< ::steward::Motors_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::steward::Motors_<ContainerAllocator> const> ConstPtr;

}; // struct Motors_

typedef ::steward::Motors_<std::allocator<void> > Motors;

typedef boost::shared_ptr< ::steward::Motors > MotorsPtr;
typedef boost::shared_ptr< ::steward::Motors const> MotorsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::steward::Motors_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::steward::Motors_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace steward

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'steward': ['/home/pawel/AGV/Pepperl/src/steward/msg', '/home/pawel/AGV/Pepperl/devel/share/steward/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::steward::Motors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::steward::Motors_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::steward::Motors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::steward::Motors_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::steward::Motors_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::steward::Motors_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::steward::Motors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "70b13c5ef9c65dbf694e40488c676596";
  }

  static const char* value(const ::steward::Motors_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x70b13c5ef9c65dbfULL;
  static const uint64_t static_value2 = 0x694e40488c676596ULL;
};

template<class ContainerAllocator>
struct DataType< ::steward::Motors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "steward/Motors";
  }

  static const char* value(const ::steward::Motors_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::steward::Motors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 motor1_pwm\n\
int16 motor2_pwm\n\
";
  }

  static const char* value(const ::steward::Motors_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::steward::Motors_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motor1_pwm);
      stream.next(m.motor2_pwm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Motors_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::steward::Motors_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::steward::Motors_<ContainerAllocator>& v)
  {
    s << indent << "motor1_pwm: ";
    Printer<int16_t>::stream(s, indent + "  ", v.motor1_pwm);
    s << indent << "motor2_pwm: ";
    Printer<int16_t>::stream(s, indent + "  ", v.motor2_pwm);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STEWARD_MESSAGE_MOTORS_H
